CREATE TABLE IF NOT EXISTS users
	(
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	username VARCHAR NOT NULL,
	created_ts INTEGER NOT NULL DEFAULT CURRENT_TIMESTAMP,
	human BOOLEAN NOT NULL DEFAULT TRUE
	);

CREATE TABLE IF NOT EXISTS users_auth_keys
	(
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	users_id INTEGER NOT NULL REFERENCES users(id),
	publickey VARCHAR NOT NULL,
	privatekey VARCHAR NOT NULL
	);

INSERT INTO users (username, human)
	VALUES
		(
		"home_server",
		FALSE
		);
